### ISSUE TITLE
В чем отличие от @vkontakte/create-vk-mini-app ?

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/create-vkui-app#45]
В чем отличие от [@vkontakte/create-vk-mini-app](https://github.com/VKCOM/create-vk-mini-app) ?

**Comment by SevereCloud** [comment]
Привет, [create-vk-mini-app](https://github.com/VKCOM/create-vk-mini-app) предназначен для создания мини приложений, [create-vkui-app](https://github.com/VKCOM/create-vkui-app) для веба
